# NumPy Array'i Oluşturmak

In [3]:
import numpy as np

In [4]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [5]:
a = np.array([1,2,3,4,5])

In [6]:
type(a)

numpy.ndarray

In [8]:
#sifirdan array olusturma

In [10]:
np.zeros(10 , dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.ones((3,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [14]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [15]:
np.arange(0,31, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [16]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [17]:
np.random.normal(10,4, (3,4))

array([[ 4.00513467,  8.96636824,  9.59467483,  9.76017561],
       [13.21802299,  8.17888806, 16.99335439, 19.36244482],
       [10.70540289,  7.67093928,  2.50941988, 13.94042973]])

In [18]:
np.random.randint(0,10, (3,3))

array([[1, 4, 1],
       [1, 3, 6],
       [1, 5, 3]])

 # Özellikleri

* **ndim:** boyut sayısı
* **shape:** boyut bilgisi
* **size:** toplam eleman sayısı
* **dtype:** array veri tipi

In [8]:
import numpy as np

In [15]:
np.random.randint(10, size = 10)

array([9, 3, 9, 9, 1, 5, 4, 9, 8, 3])

In [17]:
a = np.random.randint(10, size = 10)

In [18]:
a.ndim

1

In [19]:
a.shape

(10,)

In [20]:
a.size

10

In [21]:
a.dtype

dtype('int32')

In [29]:
b = np.random.randint(10, size = (3,5))

In [30]:
b

array([[5, 0, 4, 7, 7],
       [6, 8, 1, 1, 3],
       [0, 3, 2, 1, 0]])

In [31]:
b.ndim

2

In [32]:
b.shape

(3, 5)

In [33]:
b.size

15

In [34]:
b.dtype

dtype('int32')

# Yeniden Şekillendirme (reshaping)

In [35]:
import numpy as np

In [38]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
a = np.arange(1,10)

In [48]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
a.ndim #vektör

1

In [57]:
b = a.reshape((1,9)) #Matris boyutu:2 dir. Fakat tek bir boyutun taşıdığı bilgiyi taşır.

In [58]:
b.ndim

2

 # Array Birlestirme (Concatenation)

In [59]:
import numpy as np

In [60]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [61]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [62]:
z = np.array([7,8,9])

In [63]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
#iki boyut

In [66]:
a = np.array([[1,2,3],
              [4,5,6]])

In [67]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [73]:
#Satır bazında değil de sütun bazında birleştirmek istersek "axis" argümanını kullanıyoruz

In [74]:
np.concatenate([a,a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Array Ayırma (Splitting) 

In [75]:
import numpy as np

In [76]:
x = np.array([7,11,22,17,3,12,54,41])

In [91]:
np.split(x, [3,5])

[array([ 7, 11, 22]), array([17,  3]), array([12, 54, 41])]

In [92]:
a,b,c = np.split(x, [3,5])

In [93]:
a

array([ 7, 11, 22])

In [94]:
b

array([17,  3])

In [95]:
c

array([12, 54, 41])

#iki boyutlu array

In [107]:
m = np.arange(16).reshape(4,4)

In [97]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [108]:
np.vsplit(m, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [112]:
ust, alt = np.vsplit(m, [2])

In [113]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [114]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [115]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [116]:
np.hsplit(m, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [120]:
sag, sol = np.hsplit(m, [2])

In [121]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [122]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

# Array Sıralama (Sorting)

In [123]:
import numpy as np

In [124]:
v = np.array([9,4,7,1,5])

In [126]:
v

array([9, 4, 7, 1, 5])

In [127]:
np.sort(v)

array([1, 4, 5, 7, 9])

In [128]:
v

array([9, 4, 7, 1, 5])

In [129]:
v.sort()

In [130]:
v

array([1, 4, 5, 7, 9])

In [131]:
#iki boyutlu array sıralama

In [132]:
np.random.normal(20,5, (3,3))

array([[18.62948642, 13.03151714, 19.15107007],
       [10.5001884 , 16.89094355, 23.53552206],
       [18.06688978, 24.02878007, 21.20943793]])

In [133]:
m = np.random.normal(20,5, (3,3))

In [134]:
m

array([[18.39809399, 27.45639957, 24.27814281],
       [20.67687165, 24.87329847, 26.07303529],
       [22.39748487, 20.67735239, 17.51627593]])

In [135]:
np.sort(m, axis = 0)

array([[18.39809399, 20.67735239, 17.51627593],
       [20.67687165, 24.87329847, 24.27814281],
       [22.39748487, 27.45639957, 26.07303529]])

In [136]:
np.sort(m, axis = 1)

array([[18.39809399, 24.27814281, 27.45639957],
       [20.67687165, 24.87329847, 26.07303529],
       [17.51627593, 20.67735239, 22.39748487]])

# Index ile Elemanlara Erişmek

In [137]:
import numpy as np

In [138]:
a = np.random.randint(10, size = 10)
a

array([2, 1, 0, 7, 6, 6, 8, 6, 5, 3])

In [139]:
a[0]

2

In [140]:
a[-1]

3

In [141]:
a[0] = 11

In [142]:
a[0]

11

In [143]:
m = np.random.randint(10, size = (3,5))

In [144]:
m

array([[8, 0, 3, 7, 1],
       [5, 1, 8, 3, 0],
       [5, 8, 0, 9, 6]])

In [145]:
m[0,0]

8

In [146]:
m[1,4]

0

In [147]:
m[1,4] = 88

In [148]:
m

array([[ 8,  0,  3,  7,  1],
       [ 5,  1,  8,  3, 88],
       [ 5,  8,  0,  9,  6]])

# Slicing ile Elemanlara Erişmek (Array Alt Kümesine Erişmek)

In [149]:
import numpy as np

In [151]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [155]:
a[:5]

array([20, 21, 22, 23, 24])

In [156]:
a[1::2]

array([21, 23, 25, 27, 29])

In [157]:
#iki boyutlu slice islemleri

In [168]:
b = np.arange(1,26).reshape((5,5))
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [164]:
b[:,0]

array([1, 4, 7])

In [169]:
b[:,4]

array([ 5, 10, 15, 20, 25])

In [171]:
b[0:2, 0:3] # 0 dan 2 ye kadar satırları al, 3 e kadar sütunları al

array([[1, 2, 3],
       [6, 7, 8]])

In [172]:
b[1:3, 0:2]

array([[ 6,  7],
       [11, 12]])

# Alt Küme Üzerinde İşlem Yapmak

In [173]:
import numpy as np

In [174]:
a = np.random.randint(10, size = (5,5))
a

array([[6, 5, 8, 7, 9],
       [3, 3, 5, 2, 0],
       [8, 3, 0, 2, 9],
       [9, 0, 3, 6, 5],
       [1, 3, 0, 1, 6]])

In [175]:
alt_a = a[0:3,0:2]
alt_a

array([[6, 5],
       [3, 3],
       [8, 3]])

In [176]:
alt_a[0,0] = 9999
alt_a[1,1] = 888

In [177]:
alt_a

array([[9999,    5],
       [   3,  888],
       [   8,    3]])

In [179]:
a

array([[9999,    5,    8,    7,    9],
       [   3,  888,    5,    2,    0],
       [   8,    3,    0,    2,    9],
       [   9,    0,    3,    6,    5],
       [   1,    3,    0,    1,    6]])

In [180]:
m = np.random.randint(10, size = (5,5))
m

array([[1, 6, 4, 2, 8],
       [3, 3, 3, 7, 3],
       [3, 8, 7, 6, 4],
       [5, 8, 3, 8, 2],
       [8, 6, 6, 3, 4]])

In [181]:
alt_b = m[0:3, 0:2].copy()
alt_b

array([[1, 6],
       [3, 3],
       [3, 8]])

In [183]:
alt_b[0,0] = 7777

In [184]:
alt_b

array([[7777,    6],
       [   3,    3],
       [   3,    8]])

In [185]:
m

array([[1, 6, 4, 2, 8],
       [3, 3, 3, 7, 3],
       [3, 8, 7, 6, 4],
       [5, 8, 3, 8, 2],
       [8, 6, 6, 3, 4]])

# Fancy Index ile Elemanlara Erişmek

In [186]:
import numpy as np

In [187]:
v = np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [190]:
v[1]

3

In [191]:
v[3]

9

In [192]:
v[5]

15

In [193]:
#Bir arada görmek istiyorsak

In [194]:
[v[1], v[3], v[5]]

[3, 9, 15]

In [195]:
al_getir = [1,3,5]

In [196]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [197]:
v[al_getir]

array([ 3,  9, 15])

In [198]:
#iki boyutta fancy

In [199]:
m = np.arange(9).reshape((3,3))

In [200]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [201]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [202]:
m[satir, sutun]

array([1, 5])

In [203]:
#basit index ile fancy index

In [204]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [205]:
m[0, [1,2]] # klasik index

array([1, 2])

In [210]:
#slice ile fancy

In [211]:
m[0:, [1,2]] # 0 dan sona kadar git

array([[1, 2],
       [4, 5],
       [7, 8]])

# Koşullu Eleman Islemleri

In [212]:
import numpy as np

In [213]:
v = np.array([1,2,3,4,5])

In [214]:
v > 3

array([False, False, False,  True,  True])

In [215]:
v[v <3]

array([1, 2])

In [216]:
v[v>=2]

array([2, 3, 4, 5])

In [217]:
v

array([1, 2, 3, 4, 5])

In [218]:
v*2

array([ 2,  4,  6,  8, 10])

In [219]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [220]:
v*5/10

array([0.5, 1. , 1.5, 2. , 2.5])

In [221]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)

# Matematiksel Islemler

In [222]:
import numpy as np

In [223]:
v = np.array([1,2,3,4,5])

In [224]:
v - 1

array([0, 1, 2, 3, 4])

In [225]:
v / 3

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [226]:
#ufunc

In [227]:
np.subtract(v,1)

array([0, 1, 2, 3, 4])

In [228]:
np.add(v,1)

array([2, 3, 4, 5, 6])

In [229]:
np.multiply(v,4)

array([ 4,  8, 12, 16, 20])

In [230]:
np.divide(v,3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [231]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [232]:
v**3

array([  1,   8,  27,  64, 125], dtype=int32)

In [233]:
np.power(v,3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [234]:
v % 2

array([1, 0, 1, 0, 1], dtype=int32)

In [235]:
np.mod(v,2)

array([1, 0, 1, 0, 1], dtype=int32)

In [237]:
np.absolute(np.array([-3]))

array([3])

In [238]:
np.sin(360)

0.9589157234143065

In [239]:
np.cos(180)

-0.5984600690578581

In [240]:
v = np.array([1,2,3])

In [241]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [242]:
?np #numpy dökümantasyonunu açar

Object `np #numpy dökümantasyonunu açar` not found.


# NumPy ile Iki Bilinmeyenli Denklem Cözümü

In [243]:
import numpy as np

5 * x0 + x1 = 12

x0 + 3 * x1 = 10

In [244]:
a = np.array([[5,1],[1,3]])
b = np.array([12,10])

In [245]:
a

array([[5, 1],
       [1, 3]])

In [246]:
b

array([12, 10])

In [247]:
x = np.linalg.solve(a, b)
x

array([1.85714286, 2.71428571])